#!/usr/bin/env ansible-playbook -i inventory
---

- name: Provision the instances
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - include: tasks/securitygroup.yaml name="webservers"
    - include: tasks/instance.yaml name="devops-task" securitygroup="webservers" keypair="Devops_Test"